(function (cjs, an) {

var p; // shortcut to reference prototypes
var lib={};var ss={};var img={};
lib.ssMetadata = [];


(lib.AnMovieClip = function(){
	this.actionFrames = [];
	this.ignorePause = false;
	this.gotoAndPlay = function(positionOrLabel){
		cjs.MovieClip.prototype.gotoAndPlay.call(this,positionOrLabel);
	}
	this.play = function(){
		cjs.MovieClip.prototype.play.call(this);
	}
	this.gotoAndStop = function(positionOrLabel){
		cjs.MovieClip.prototype.gotoAndStop.call(this,positionOrLabel);
	}
	this.stop = function(){
		cjs.MovieClip.prototype.stop.call(this);
	}
}).prototype = p = new cjs.MovieClip();
// symbols:



(lib.B1 = function() {
	this.initialize(img.B1);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,656,614);


(lib.B2 = function() {
	this.initialize(img.B2);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,45,40);


(lib.B3 = function() {
	this.initialize(img.B3);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,45,39);


(lib.bg = function() {
	this.initialize(img.bg);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,1080,800);


(lib.bg2 = function() {
	this.initialize(img.bg2);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,1080,800);


(lib.light = function() {
	this.initialize(img.light);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,307,961);// helper functions:

function mc_symbol_clone() {
	var clone = this._cloneProps(new this.constructor(this.mode, this.startPosition, this.loop, this.reversed));
	clone.gotoAndStop(this.currentFrame);
	clone.paused = this.paused;
	clone.framerate = this.framerate;
	return clone;
}

function getMCSymbolPrototype(symbol, nominalBounds, frameBounds) {
	var prototype = cjs.extend(symbol, cjs.MovieClip);
	prototype.clone = mc_symbol_clone;
	prototype.nominalBounds = nominalBounds;
	prototype.frameBounds = frameBounds;
	return prototype;
	}


(lib.bg2_1 = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.instance = new lib.bg();
	this.instance.setTransform(0,4);

	this.instance_1 = new lib.bg();

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.instance_1},{t:this.instance}]}).wait(1));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,1080,804);


(lib.tittle = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// 圖層_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#724494").s().p("ACxWcQipDJj5B3IgHgTQDxilCdj/QgUh2gFhDQgGhTAFiBIAihDQABB1ALBNQAKBBAcBnQB2jgBFktIiVAAIAWguICrAAIBVhzIAnAuQArA2AYAjQgHAageAAIhBAAQhnGOirD4QBNCxCgBsIgGAPQhYAVglBmQh7h4g8jLgAq/bOQCAjYBQkqQA7jjAulaIiIAAIgDguIGnAAIBUhvIAkAtQApA1AXAhQgKAagbAAIk6AAQgVCCgVBiIgJAuQg4EMhMC3QhcDeiQCagA53bLQBsh/BIjPQA8iqAfjOICcAiQgOAlgpACQggCLgtBzIgTAtQhhDlipB+gAMhbZIC8zxIB4BIIgRAuIiiRCQgBAQgjAUQglAVgkAAgAmZabQABgagJgNQgRgfg6gTIAEgXIA8AGQAmADAOAAQAPAAAJgEQAJgEAKgJQAfggAmiYQAmibA0kvIhqAAIAJguIBcAAIBJhRIBeB5QgSAUgmAHQg8FkguCoQgtCigzA0Qg9A+hTAAQAFgmAAgVgAW6bUIARhwInwAAIAGguIHxAAIAtkzInwAAIAGgrIHwAAIAtksInxAAIAIguIHwAAIArkgInwAAIAQguIBfAAQAphzAnijIC2ApQgLAignADQhPBuhWBaIFMAAIBNhbIBtCEQgUAVgoAMIieQpQgEALglASQgoAUgfAAgAwSbQQiTAAhHhBQhOhIgUi1IATgsQAQBHAdAuQAdAtAsAZIBiqZIkEAAIgDguIHuAAIBRhnIAlAqQAqAxAXAhQgHAZgeAAIkMAAIhnK5QApAGA9AAQCkAAA5gBIgEAWQgaAGgSAhQgRAfgGAugEAjqAaqQiBAAgvguQgzgyAUh/IBhqUICBBDIgXAuIhSIqQgGAnAZAQQAXANA6AAIH2AAQA/AAAbgJQAggKAUggQASgcAghPQAdhGAdhSIAOAAIgmERQAoARALALQANANgDAYQgJA8g7AbQhFAhihAAgA/BZ1QgHgbAMggQAMgdAZgVQAfgkAchAQAehIADg+IAWAAQAMBxgRBfQgQBUgiAwQgXAfgiACIgEAAQgfAAgJgegA7xYkQAThAAKhSQAHhIgCg/IASgFQAzBFAJBLQAJA/gWA0QgTAvgeAKQgGACgGAAQgXAAgPgggA5DXeQAIg1gHhFQgGg9gPgyIAPgGQBCAsAYA9QAUAygNAwQgMArgcANQgJAEgIAAQgUAAgPgYgA96RWQAdgIANgJQAvgsA+hPQA6hLA5hZQhPAjhCAZQgQAXgSAKIgcilQAYgIAMgJQA0g7BIiQQBDiCAjhlICBBbQgNAcgigEQgyBRhIBeQhMBkhCBDQBHADBggDQAxhPAmhPIBcBZIgKApQgLAAgHgCQhBBchjBvQhoBzheBUQA8gEDGgRIAEAlQiJA6ihA4QgTAagTAHgA3xSyQACgfgCgrIgEglQgKhPgZhIIASgJQBHAzAdBDQAYA4gLA0QgJAvgdAQQgKAFgJAAQgTAAgQgXgAv4TBIAHguIBDAAIBShxIAjAuQAoA1AVAiQgJAagbAAgEAskAQyIAUiKIoNAAIAXguIH9AAIBBm1IrLAAIgFguILJAAIBLhWIBvCBQgRAYgtANIhRIjQgDAJglAPQgoAQgdAAgAhAQaQBQiVBKjJQBMjQAwjSICqAuQgGAQgMAKQgOALgUABQgzCRg8CFIgWAuQgXAugWApIgdAwQhVCRhaBdgA1qL2QgWgPABgfIAKgpQAIgPANgTQAjgYAcgyQAegzARhHIARABQAFA3gBAlIgDAtQgPCUhKAhQgNAFgLAAQgOAAgLgHgAs0LbIAxiYIm9AAIADgtIG5AAIBJhPIBXCFQgHAJgMAEQgJADgUACQhSBRhAA0gAj2I0QABg7gUhOQgRhDgag6IAOgJQBhAlAqBBQAiA2gKA7QgIA1glAUQgNAIgNAAQgXAAgVgZgAv8HwQAHg3gMhAQgKg6gVgsIAMgLQBcAcAjA6QAeAwgOA2QgNAxgmARQgLAFgMAAQgYAAgVgbgAtTpCQiQC6jaByIgIgVQDjijCEjoQgIiPAPi3IAlhLQgDCtAQB2QA2h0ApiMQAlh/AgiiIg9AAIATguIA0AAIBNhiIAhAoQAnAuAXAgQgJAagdAAIgpAAQgwDUg1CXQg8CthPCDQAyCyBxBgIgHAPQhPAVgmBeQhRhsgfjAgA6DkbIB+rlQhGBShQBLIgMgQQBSh0BbijQBWiZAyh2IBsBPIAskFICFAaQgFAPgLAIQgNAKgaAFIgvERIBJAAIBPnSIB7ARQgFAPgJAJQgLAKgTAEIhGGbIBGAAIA3lHIB9AQQgFAQgKAJQgLAKgUAEIg4FHQgCAJgZAMQgbAMgXAAIgQAAIAHgqIjgAAIgjAqIhSg9QAPgRAQgNIAGgmQgKACgQgCQg7BYhKBfIBHAkQgKAXggAGIh+LiQgCAMgfASQgiAUggAAgAnhk3QDxhhCJiEQB2hyBBioIm0AAIgEgtIHJAAQAehbAah/QjYAMjDgJIACgbQDNgUDpgyQDpgzCMg2IBeCeQgMAMgUgBQgVgBgYgPQiCAXieAMQgkCagZBLIADAtQAnChCABgQBuBUC1AkIgDARQhPAYgqBxQiihHhUhyQhch9gVjQQhKDDiOB3QikCHkoBKgEgwzgEuQB2igBGjtQAxioAqkVIBSoqIB+A/IgZAuIhCG7QgXCfgaBqIgMAuQgtCnhFB+QhTCWh7BpgEgi1gGNQgMgTgWgMQgZgNgogIIAEgYIBBAHQBFAGAQAAQAQAAAIgJQAHgIACgSIAzlUIkaAAIhJHvQgBALgcAOQgiASgnAAIgUAAIBQoaIkCAAIAMguID8AAIAylPIjyAAIAHguIDyAAIAwlHIjyAAIAaguIJfAAIBHhXIByCAQgYAdgoAIIihQ2QgNBbggAlQgrAwhnALQAFhMgSgdgEgk9gNxIEaAAIAylPIkaAAgEgkEgTuIEaAAIAwlHIkZAAgA37k5QB+iiA5lPIAYiNICGARQgLAiglAGIgPBYQhDFqjHCVgAzJokQAagSAKgNQAIgLADgUIA6lVICOAUQgMAogvAIIgvEWQBJglA5ghIAGAVQhaBbhyBsQgMAagYARgAEds2IgEgtID4AAIBch3IAnAwQArA3AYAkQgKAZgcAAgAvEvIQBGiaBDjSQBDjPAwjQICNAhQgOAkglACQgoCCg7CXIgTAuQgjBYgpBSIgeA8QgxBegyBHgA1LwfIgDguIEuAAIA/hVIAZAkQAdAqAPAbQgJAagcAAgAliyfQBUhmBWiXQBaidBBikICWBHQgRAfgmgEQgHAPgyBTIgcAuQiXDdirB+gAAZziQAEgygRg8QgNg1gXglIAPgLQBVAZAlA0QAdAqgMAxQgLAsggAQQgMAFgLAAQgWAAgRgWgADWzoQBAhfBAiDQBDiKAwiKICYBFQgQAhgkgEQgLATgwBQIgeAuQhsCkiFBtgAJCzzQABgxgYg4QgUgygggkIAMgNQBfALAtAuQAkAmgGAyQgGAughAVQgPAJgOAAQgUAAgTgRgA5g0yQBJhWBUh+QBOh0AwhdIB4BfQgIAOgLAFQgMAEgUgFQhDBThWBTQhiBghbA/gAIP3rIAfguICJAAIBVhrIAjAsQAnAyAWAiQgKAZgcAAgAAt3rIAcguIBuAAIBOhiIAeApQAjAuATAgQgHAZgdAAg");
	this.shape.setTransform(0,-0.025);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.tittle, new cjs.Rectangle(-312.3,-175.9,624.7,351.8), null);


(lib.line02 = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#7A43A2").s().p("Eg5uAMbQG1hNGUieQGHiZEZi/QDiibCSirQheh1goh6QglhzANhuQAMhqA2hIQA2hIBGgBQAxgBAqAXQApAXAcAsQAxBNgEBwQgFBxg5B0QgzBohWBpQCgC7EiCbQFECtHSB2QNsDgTlAGQRQAGPhidIAAAfQviCcxTgGQzlgGtvjgQnUh4lHiuQkliciki/QiVCujkCbQkcDBmHCZQmZCgm7BOgA9UreQgyBAgMBjQgLBoAiBsQAlBzBYBvQBRhkAwhjQA1hrAFhqQAFhqgshFQgXglgigTQgigTgoAAIgEAAQg1ABguA8g");
	this.shape.setTransform(0.025,0.0229);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.line02, new cjs.Rectangle(-369.4,-82.5,738.9,165.1), null);


(lib.line01 = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#7A43A2").s().p("EAoxAHNQlehmqukLQpLjjk9hoQoRisnthWQvxiwz5BRQp/Aom/BOIAAgeQG/hOJ/gpQT7hRP1CxQHtBWIUCtQE9BoJNDkQKsEKFcBlQJCCoIQAUIgBAeQoUgUpEiog");
	this.shape.setTransform(0,0.026);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.line01, new cjs.Rectangle(-372.2,-64.9,744.4,129.9), null);


(lib.lightpurple = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.instance = new lib.light();
	this.instance.setTransform(-153.5,-480.5);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.lightpurple, new cjs.Rectangle(-153.5,-480.5,307,961), null);


(lib.bg2_2 = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.instance_2 = new lib.bg2();
	this.instance_2.setTransform(-540,-400);

	this.timeline.addTween(cjs.Tween.get(this.instance_2).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.bg2_2, new cjs.Rectangle(-540,-400,1080,800), null);


(lib.B3_1 = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.instance = new lib.B3();
	this.instance.setTransform(-22.5,-19.5);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.B3_1, new cjs.Rectangle(-22.5,-19.5,45,39), null);


(lib.B2_1 = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.instance = new lib.B2();
	this.instance.setTransform(-22.5,-20);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.B2_1, new cjs.Rectangle(-22.5,-20,45,40), null);


(lib.B1_1 = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.instance = new lib.B1();
	this.instance.setTransform(-328,-307);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.B1_1, new cjs.Rectangle(-328,-307,656,614), null);


// stage content:
(lib.Gumh5 = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	this.actionFrames = [72];
	// timeline functions:
	this.frame_72 = function() {
		this.stop();
	}

	// actions tween:
	this.timeline.addTween(cjs.Tween.get(this).wait(72).call(this.frame_72).wait(1));

	// b_mask (mask)
	var mask = new cjs.Shape();
	mask._off = true;
	mask.graphics.p("ECMSCAoIjIlaIl6AAIjIFaImXAAIjIlaIl6AAIjIFaImXAAIjJlaIl5AAIjJFaImXAAIjIlaIl6AAIjIFaImXAAIjIlaIl6AAIjIFaImYAAIjIlaIl6AAIjIFaImXAAIjIlaIl6AAIjIFaImXAAIjIlaIl0AAIjGFaImYAAIjIlaIl6AAIjIFaImXAAIjIlaIl6AAIjIFaImXAAIjIlaIl6AAIjIFaImYAAIjHlaIl7AAIjIFaImXAAIjIlaIl6AAIjIFaImXAAIjIlaIl7AAIjHFaImYAAIjIlaIl6AAIjIFaImXAAIjIlaImHAAIjMliIDMlhIGLAAIC+lIIjClQImHAAIjMlhIDMlhIGLAAIC+lIIjClQImHAAIjMlhIDMlhIGLAAIC+lJIjClQImHAAIjMlhIDMlhIGLAAIC+lIIjClQImHAAIjMlhIDMlhIGLAAIC+lJIjClQImHAAIjMlhIDMlhIGLAAIC9lHIjBlPImHAAIjMlhIDMlgIGLAAIC+lJIjClQImHAAIjMlhIDMlhIGLAAIC+lIIjClRImHAAIjMlhIDMlgIGLAAIC+lJIjClQImHAAIjMlhIDMlgIGLAAIC+lJIjClQImHAAIjMlhIDMlhIGLAAIC+lIIjClRImHAAIjMlhIDMlgIGLAAIDElTIGXAAIDEFTIGDAAIDDlTIGYAAIDDFTIGDAAIDElTIGXAAIDEFTIGCAAIDElTIGXAAIDEFTIGDAAIDDlTIGYAAIDDFTIGDAAIDElTIGXAAIDEFTIGCAAIDElTIGXAAIDEFTIGDAAIDDlTIGYAAIDCFTIF8AAIDElTIGXAAIDEFTIGCAAIDElTIGXAAIDEFTIGDAAIDDlTIGYAAIDDFTIGDAAIDElTIGXAAIDEFTIGCAAIDElTIGXAAIDEFTIGDAAIDElTIGXAAIDEFTIGCAAIDElTIGXAAIDEFTIGDAAIDDlTIGYAAIDMFhIjHFWIDHFXIjHFXIDHFWIjHFXIDHFWIjHFXIDHFXIjHFWIDHFXIjGFWIDGFXIjHFWIDHFXIjHFXIDHFWIjHFXIDHFWIjHFXIDHFXIjHFWIDHFXIjGFVIDGFWIjHFWIDHFXIjHFWIDHFXIjHFXIDHFWIjHFXIDHFXIjHFWIDHFXIjHFWIDHFXIjHFXIDHFWIjHFXIDHFXIjHFWIDHFXIjGFWIDGFXIjGFWIDGFXIjMFhgECJiB7HIC+FJIF8AAIC+lJIi+lJIl8AAgEB3BB7HIC9FJIF9AAIC+lJIi+lJIl9AAgEBkfB7HIC+FJIF8AAIC+lJIi+lJIl8AAgEBR+B7HIC+FJIF8AAIC+lJIi+lJIl8AAgEA/cB7HIC+FJIF9AAIC9lJIi9lJIl9AAgEAs7B7HIC+FJIF8AAIC+lJIi+lJIl8AAgEAaaB7HIC9FJIF9AAIC+lJIi+lJIl9AAgEAH4B7HIC+FJIF9AAIC9lJIi9lJIl9AAgEgKhB7HIC+FJIF8AAIC9lJIi9lJIl8AAgEgdDB7HIC+FJIF8AAIC/lJIi/lJIl8AAgEgvkB7HIC+FJIF8AAIC/lJIi/lJIl8AAgEhCFB7HIC+FJIF8AAIC+lJIi+lJIl8AAgEhUnB7HIC/FJIF8AAIC+lJIi+lJIl8AAgEhnIB7HIC+FJIF8AAIC/lJIi/lJIl8AAgEh5pB7HIC+FJIF8AAIC+lJIi+lJIl8AAgEiMLB7HIC/FJIF8AAIC+lJIi+lJIl8AAgECATB1sIC+FKIF8AAIC+lJIi/lKIl7AAgEBtyB1sIC+FKIF8AAIC9lJIi/lKIl6AAgEBbQB1sIC+FKIF9AAIC9lJIi/lKIl7AAgEBIvB1sIC+FKIF8AAIC9lJIi+lKIl7AAgEA2OB1sIC+FKIF8AAIC9lJIi/lKIl6AAgEAjsB1sIC+FKIF9AAIC9lJIi/lKIl7AAgEARLB1sIC+FKIF8AAIC9lJIi+lKIl7AAgEAHkB62IC9lJIi/lKIl2AAIi/FNICVEFIAlBBgEgTwB1sIC+FKIF8AAIC9lIIi+lLIl7AAgEgmRB1sIC+FKIF8AAIC9lIIi/lLIl6AAgEg4yB1sIC+FKIF8AAIC9lIIi/lLIl6AAgEhLUB1sIC+FKIF8AAIC+lIIi/lLIl7AAgEhd1B1sIC+FKIF8AAIC9lIIi+lLIl7AAgEhwXB1sIC/FKIF8AAIC9lIIi/lLIl6AAgEiC4B1sIC+FKIF8AAIC+lIIi/lLIl7AAgEiVZB1sIC+FKIF8AAIC9lIIi+lLIl7AAgECScB1jIC+lJIi+lKIl8AAIi+FJIDAFKgEB/7B1jIC+lJIi+lKIl9AAIi9FJIC/FKgEBtZB1jIC+lJIi+lKIl8AAIi9FJIC/FKgEBa4B1jIC+lJIi+lKIl8AAIi+FJIC/FKgEBIXB1jIC9lJIi9lKIl9AAIi9FJIC/FKgEA11B1jIC+lJIi+lKIl8AAIi9FJIC/FKgEAjUB1jIC+lJIi+lKIl9AAIi9FJIC/FKgEAQzB1jIC9lJIi9lKIl9AAIi9FJIC/FKgEgBsB1jIDAlNIi7lGIl8AAIi+FIIC/FLgEgUJB1jIC/lJIi/lKIl8AAIi9FIIC/FLgEgmqB1jIC/lJIi/lKIl8AAIi9FIIC/FLgEg5LB1jIC+lJIi+lKIl8AAIi9FIIC/FLgEhLsB1jIC+lJIi+lKIl8AAIi+FIIC/FLgEheOB1jIC/lJIi/lKIl8AAIi9FIIC/FLgEhwvB1jIC+lJIi+lKIl8AAIi+FIIC/FLgEiDQB1jIC+lJIi+lKIl8AAIi+FIIC/FLgECJPBwLIC9lIIjClQIl5AAIjDFQIC+FIgEB2tBwLIC+lIIjClQIl6AAIjCFQIC+FIgEBkMBwLIC+lIIjDlQIl5AAIjDFQIC+FIgEBRqBwLIC+lIIjClQIl6AAIjCFQIC+FIgEA/JBwLIC+lIIjDlQIl5AAIjCFQIC9FIgEAsoBwLIC9lIIjClQIl5AAIjDFQIC+FIgEAaGBwLIC+lIIjClQIl6AAIjCFQIC+FIgEAHlBwLIC+lIIjDlQIlyAAIjBFQIC8FIgEgK0BwLIC9lIIjClQIl6AAIjCFQIC+FIgEgdWBwLIC+lIIjClQIl6AAIjCFQIC+FIgEgv3BwLIC+lIIjClQIl6AAIjCFQIC9FIgEhCYBwLIC9lIIjClQIl6AAIjBFQIC9FIgEhU6BwLIC+lIIjClQIl6AAIjCFQIC+FIgEhnbBwLIC9lIIjBlQIl6AAIjCFQIC9FIgEh58BwLIC9lIIjClQIl6AAIjCFQIC+FIgECJiBltIC+FJIF8AAIC+lJIi+lJIl8AAgEB3BBltIC9FJIF9AAIC+lJIi+lJIl9AAgEBkfBltIC+FJIF8AAIC+lJIi+lJIl8AAgEBR+BltIC+FJIF8AAIC+lJIi+lJIl8AAgEA/cBltIC+FJIF9AAIC9lJIi9lJIl9AAgEAs7BltIC+FJIF8AAIC+lJIi+lJIl8AAgEAaaBltIC9FJIF9AAIC+lJIi+lJIl9AAgEAH4BltIC+FJIF9AAIC9lJIi9lJIl9AAgEgKhBltIC+FJIF8AAIC9lJIi9lJIl8AAgEgdDBltIC+FJIF8AAIC/lJIi/lJIl8AAgEgvkBltIC+FJIF8AAIC/lJIi/lJIl8AAgEhCFBltIC+FJIF8AAIC+lJIi+lJIl8AAgEhUnBltIC/FJIF8AAIC+lJIi+lJIl8AAgEhnIBltIC+FJIF8AAIC/lJIi/lJIl8AAgEh5pBltIC+FJIF8AAIC+lJIi+lJIl8AAgEiMLBltIC/FJIF8AAIC+lJIi+lJIl8AAgECATBgSIC+FJIF8AAIC+lIIi/lKIl7AAgEBtyBgSIC+FJIF8AAIC9lIIi/lKIl6AAgEBbQBgSIC+FJIF9AAIC9lIIi/lKIl7AAgEBIvBgSIC+FJIF8AAIC+lIIi/lKIl7AAgEA2OBgSIC+FJIF8AAIC9lIIi/lKIl6AAgEAjsBgSIC+FJIF9AAIC9lIIi/lKIl7AAgEARLBgSIC+FJIF8AAIC9lIIi+lKIl7AAgEABnBlbIF9AAIC9lIIi/lKIl2AAIi/FNgEgTwBgSIC+FJIF8AAIC+lIIi/lKIl7AAgEgmRBgSIC+FJIF8AAIC9lIIi/lKIl6AAgEg4yBgSIC+FJIF8AAIC9lIIi+lKIl7AAgEhLUBgSIC+FJIF8AAIC+lIIi/lKIl7AAgEhd1BgSIC+FJIF8AAIC9lIIi+lKIl7AAgEhwXBgSIC/FJIF8AAIC9lIIi/lKIl6AAgEiC4BgSIC+FJIF8AAIC+lIIi/lKIl7AAgEiVZBgSIC+FJIF8AAIC9lIIi+lKIl7AAgECScBgJIC+lJIi+lKIl8AAIi+FJIC/FKgEB/7BgJIC+lJIi+lKIl9AAIi9FJIC/FKgEBtZBgJIC+lJIi+lKIl8AAIi9FJIC/FKgEBa4BgJIC+lJIi+lKIl8AAIi+FJIC/FKgEBIXBgJIC9lJIi9lKIl9AAIi9FJIC/FKgEA11BgJIC+lJIi+lKIl8AAIi9FJIC+FKgEAjUBgJIC+lJIi+lKIl9AAIi9FJIC/FKgEAQzBgJIC9lJIi9lKIl9AAIi9FJIC/FKgEgBsBgJIDAlNIi7lGIl8AAIi+FIIC/FLgEgUJBgJIC/lJIi/lKIl8AAIi9FIIC/FLgEgmqBgJIC/lJIi/lKIl8AAIi9FIIC/FLgEg5LBgJIC+lJIi+lKIl8AAIi9FIIC+FLgEhLsBgJIC+lJIi+lKIl8AAIi+FIIC/FLgEheOBgJIC/lJIi/lKIl8AAIi9FIIC/FLgEhwvBgJIC+lJIi+lKIl8AAIi+FIIC/FLgEiDQBgJIC+lJIi+lKIl8AAIi+FIIC/FLgECJPBaxIC9lIIjClQIl5AAIjDFQIC+FIgEB2tBaxIC+lIIjClQIl6AAIjCFQIC+FIgEBkMBaxIC+lIIjDlQIl5AAIjDFQIC+FIgEBRqBaxIC+lIIjClQIl6AAIjCFQIC+FIgEA/JBaxIC+lIIjDlQIl5AAIjCFQIC9FIgEAsoBaxIC+lIIjDlQIl5AAIjDFQIC+FIgEAaGBaxIC+lIIjClQIl6AAIjCFQIC+FIgEAHlBaxIC+lIIjDlQIlyAAIjBFQIC8FIgEgK0BaxIC9lIIjClQIl6AAIjCFQIC+FIgEgdWBaxIC+lIIjClQIl6AAIjCFQIC+FIgEgv3BaxIC+lIIjClQIl6AAIjCFQIC9FIgEhCYBaxIC9lIIjClQIl6AAIjCFQIC+FIgEhU6BaxIC+lIIjClQIl6AAIjCFQIC+FIgEhnbBaxIC+lIIjClQIl6AAIjCFQIC9FIgEh58BaxIC9lIIjClQIl6AAIjCFQIC+FIgECJiBQSIC+FKIF8AAIC+lKIi+lJIl8AAgEB3BBQSIC9FKIF9AAIC+lKIi+lJIl9AAgEBkfBQSIC+FKIF8AAIC+lKIi+lJIl8AAgEBR+BQSIC+FKIF8AAIC+lKIi+lJIl8AAgEA/cBQSIC+FKIF9AAIC9lKIi9lJIl9AAgEAs7BQSIC+FKIF8AAIC+lKIi+lJIl8AAgEAaaBQSIC9FKIF9AAIC+lKIi+lJIl9AAgEAH4BQSIC+FKIF9AAIC9lKIi9lJIl9AAgEgKhBQSIC+FKIF8AAIC9lKIi9lJIl8AAgEgdDBQSIC+FKIF8AAIC/lKIi/lJIl8AAgEgvkBQSIC+FKIF8AAIC/lKIi/lJIl8AAgEhCFBQSIC+FKIF8AAIC+lKIi+lJIl8AAgEhUnBQSIC/FKIF8AAIC+lKIi+lJIl8AAgEhnIBQSIC+FKIF8AAIC/lKIi/lJIl8AAgEh5pBQSIC+FKIF8AAIC+lKIi+lJIl8AAgEiMLBQSIC/FKIF8AAIC+lKIi+lJIl8AAgECATBK4IC+FJIF8AAIC+lIIi/lKIl7AAgEBtyBK4IC+FJIF8AAIC9lIIi/lKIl6AAgEBbQBK4IC+FJIF9AAIC9lIIi/lKIl7AAgEBIvBK4IC+FJIF8AAIC+lIIi/lKIl7AAgEA2OBK4IC+FJIF8AAIC9lIIi/lKIl6AAgEAjsBK4IC+FJIF9AAIC9lIIi/lKIl7AAgEARLBK4IC+FJIF8AAIC9lIIi+lKIl7AAgEABnBQBIF9AAIC9lIIi/lKIl2AAIi/FMgEgTwBK4IC+FJIF8AAIC+lIIi/lKIl7AAgEgmRBK4IC+FJIF8AAIC9lIIi/lKIl6AAgEg4yBK4IC+FJIF8AAIC9lIIi+lKIl7AAgEhLUBK4IC+FJIF8AAIC+lIIi/lKIl7AAgEhd1BK4IC+FJIF8AAIC9lIIi+lKIl7AAgEhwXBK4IC/FJIF8AAIC9lIIi/lKIl6AAgEiC4BK4IC+FJIF8AAIC+lIIi/lKIl7AAgEiVZBK4IC+FJIF8AAIC9lIIi+lKIl7AAgECScBKuIC+lJIi+lJIl8AAIi+FIIC/FKgEB/7BKuIC+lJIi+lJIl9AAIi9FIIC/FKgEBtZBKuIC+lJIi+lJIl8AAIi9FIIC/FKgEBa4BKuIC+lJIi+lJIl8AAIi+FIIC/FKgEBIXBKuIC9lJIi9lJIl9AAIi9FIIC/FKgEA11BKuIC+lJIi+lJIl8AAIi9FIIC+FKgEAjUBKuIC+lJIi+lJIl9AAIi9FIIC/FKgEAQzBKuIC9lJIi9lJIl9AAIi9FIIC/FKgEgBsBKuIDAlNIi7lFIl8AAIi+FIIC/FKgEgUJBKuIC/lJIi/lJIl8AAIi9FIIC/FKgEgmqBKuIC/lJIi/lJIl8AAIi9FIIC/FKgEg5LBKuIC+lJIi+lJIl8AAIi9FIIC+FKgEhLsBKuIC+lJIi+lJIl8AAIi+FIIC/FKgEheOBKuIC/lJIi/lJIl8AAIi9FIIC/FKgEhwvBKuIC+lJIi+lJIl8AAIi+FIIC/FKgEiDQBKuIC+lJIi+lJIl8AAIi+FIIC/FKgECJPBFXIC9lJIjClQIl5AAIjDFQIC+FJgEB2tBFXIC+lJIjClQIl6AAIjCFQIC+FJgEBkMBFXIC+lJIjDlQIl5AAIjDFQIC+FJgEBRqBFXIC+lJIjClQIl6AAIjCFQIC+FJgEA/JBFXIC+lJIjDlQIl5AAIjCFQIC9FJgEAsoBFXIC+lJIjDlQIl5AAIjDFQIC+FJgEAaGBFXIC+lJIjClQIl6AAIjCFQIC+FJgEAHlBFXIC+lJIjDlQIlyAAIjBFQIC8FJgEgK0BFXIC9lJIjClQIl6AAIjCFQIC+FJgEgdWBFXIC+lJIjClQIl6AAIjCFQIC+FJgEgv3BFXIC+lJIjClQIl6AAIjCFQIC9FJgEhCYBFXIC9lJIjClQIl6AAIjCFQIC+FJgEhU6BFXIC+lJIjClQIl6AAIjCFQIC+FJgEhnbBFXIC+lJIjClQIl6AAIjCFQIC9FJgEh58BFXIC9lJIjClQIl6AAIjCFQIC+FJgECJiA64IC+FJIF8AAIC+lJIi+lJIl8AAgEB3BA64IC9FJIF9AAIC+lJIi+lJIl9AAgEBkfA64IC+FJIF8AAIC+lJIi+lJIl8AAgEBR+A64IC+FJIF8AAIC+lJIi+lJIl8AAgEA/cA64IC+FJIF9AAIC9lJIi9lJIl9AAgEAs7A64IC+FJIF8AAIC+lJIi+lJIl8AAgEAaaA64IC9FJIF9AAIC+lJIi+lJIl9AAgEAH4A64IC+FJIF9AAIC9lJIi9lJIl9AAgEgKhA64IC+FJIF8AAIC9lJIi9lJIl8AAgEgdDA64IC+FJIF8AAIC/lJIi/lJIl8AAgEgvkA64IC+FJIF8AAIC/lJIi/lJIl8AAgEhCFA64IC+FJIF8AAIC+lJIi+lJIl8AAgEhUnA64IC/FJIF8AAIC+lJIi+lJIl8AAgEhnIA64IC+FJIF8AAIC/lJIi/lJIl8AAgEh5pA64IC+FJIF8AAIC+lJIi+lJIl8AAgEiMLA64IC/FJIF8AAIC+lJIi+lJIl8AAgECATA1dIC+FJIF8AAIC+lIIi/lKIl7AAgEBtyA1dIC+FJIF8AAIC9lIIi/lKIl6AAgEBbQA1dIC+FJIF9AAIC9lIIi/lKIl7AAgEBIvA1dIC+FJIF8AAIC+lIIi/lKIl7AAgEA2OA1dIC+FJIF8AAIC9lIIi/lKIl6AAgEAjsA1dIC+FJIF9AAIC9lIIi/lKIl7AAgEARLA1dIC+FJIF8AAIC9lIIi+lKIl7AAgEABnA6mIF9AAIC9lIIi/lKIl2AAIi/FNgEgTwA1dIC+FJIF8AAIC+lHIi/lLIl7AAgEgmRA1dIC+FJIF8AAIC9lHIi/lLIl6AAgEg4yA1dIC+FJIF8AAIC9lHIi+lLIl7AAgEhLUA1dIC+FJIF8AAIC+lHIi/lLIl7AAgEhd1A1dIC+FJIF8AAIC9lHIi+lLIl7AAgEhwXA1dIC/FJIF8AAIC9lHIi/lLIl6AAgEiC4A1dIC+FJIF8AAIC+lHIi/lLIl7AAgEiVZA1dIC+FJIF8AAIC9lHIi+lLIl7AAgECScA1UIC+lJIi+lKIl8AAIi+FJIC/FKgEB/7A1UIC+lJIi+lKIl9AAIi9FJIC/FKgEBtZA1UIC+lJIi+lKIl8AAIi9FJIC/FKgEBa4A1UIC+lJIi+lKIl8AAIi+FJIC/FKgEBIXA1UIC9lJIi9lKIl9AAIi9FJIC/FKgEA11A1UIC+lJIi+lKIl8AAIi9FJIC+FKgEAjUA1UIC+lJIi+lKIl9AAIi9FJIC/FKgEAQzA1UIC9lJIi9lKIl9AAIi9FJIC/FKgEgBsA1UIDAlNIi7lGIl8AAIi+FIIC/FLgEgUJA1UIC/lJIi/lKIl8AAIi9FIIC/FLgEgmqA1UIC/lJIi/lKIl8AAIi9FIIC/FLgEg5LA1UIC+lJIi+lKIl8AAIi9FIIC+FLgEhLsA1UIC+lJIi+lKIl8AAIi+FIIC/FLgEheOA1UIC/lJIi/lKIl8AAIi9FIIC/FLgEhwvA1UIC+lJIi+lKIl8AAIi+FIIC/FLgEiDQA1UIC+lJIi+lKIl8AAIi+FIIC/FLgECJPAv8IC9lIIjClQIl5AAIjDFQIC+FIgEB2tAv8IC+lIIjClQIl6AAIjCFQIC+FIgEBkMAv8IC+lIIjDlQIl5AAIjDFQIC+FIgEBRqAv8IC+lIIjClQIl6AAIjCFQIC+FIgEA/JAv8IC+lIIjClQIl6AAIjCFQIC9FIgEAsoAv8IC+lIIjDlQIl5AAIjDFQIC+FIgEAaGAv8IC+lIIjClQIl6AAIjCFQIC+FIgEAHlAv8IC+lIIjDlQIlyAAIjBFQIC8FIgEgK0Av8IC9lIIjClQIl6AAIjCFQIC+FIgEgdWAv8IC+lIIjClQIl6AAIjCFQIC+FIgEgv3Av8IC+lIIjClQIl6AAIjCFQIC9FIgEhCYAv8IC9lIIjClQIl6AAIjCFQIC+FIgEhU6Av8IC+lIIjClQIl6AAIjCFQIC+FIgEhnbAv8IC+lIIjClQIl6AAIjCFQIC9FIgEh58Av8IC9lIIjClQIl6AAIjCFQIC+FIgECJiAldIC+FKIF8AAIC+lKIi+lJIl8AAgEB3BAldIC9FKIF9AAIC+lKIi+lJIl9AAgEBkfAldIC+FKIF8AAIC+lKIi+lJIl8AAgEBR+AldIC+FKIF8AAIC+lKIi+lJIl8AAgEA/cAldIC+FKIF9AAIC9lKIi9lJIl9AAgEAs7AldIC+FKIF8AAIC+lKIi+lJIl8AAgEAaaAldIC9FKIF9AAIC+lKIi+lJIl9AAgEAH4AldIC+FKIF9AAIC9lKIi9lJIl9AAgEgKhAldIC+FKIF8AAIC9lKIi9lJIl8AAgEgdDAldIC+FKIF8AAIC/lKIi/lJIl8AAgEgvkAldIC+FKIF8AAIC/lKIi/lJIl8AAgEhCFAldIC+FKIF8AAIC+lKIi+lJIl8AAgEhUnAldIC/FKIF8AAIC+lKIi+lJIl8AAgEhnIAldIC+FKIF8AAIC/lKIi/lJIl8AAgEh5pAldIC+FKIF8AAIC+lKIi+lJIl8AAgEiMLAldIC/FKIF8AAIC+lKIi+lJIl8AAgECATAgDIC+FJIF8AAIC+lIIi/lKIl7AAgEBtyAgDIC+FJIF8AAIC9lIIi/lKIl6AAgEBbQAgDIC+FJIF9AAIC9lIIi/lKIl7AAgEBIvAgDIC+FJIF8AAIC+lIIi/lKIl7AAgEA2OAgDIC+FJIF8AAIC9lIIi/lKIl6AAgEAjsAgDIC+FJIF9AAIC9lIIi/lKIl7AAgEARLAgDIC+FJIF8AAIC9lIIi+lKIl7AAgEABnAlMIF9AAIC9lIIi/lKIl2AAIi/FMgEgTwAgDIC+FJIF8AAIC+lIIi/lKIl7AAgEgmRAgDIC+FJIF8AAIC9lIIi/lKIl6AAgEg4yAgDIC+FJIF8AAIC9lIIi+lKIl7AAgEhLUAgDIC+FJIF8AAIC+lIIi/lKIl7AAgEhd1AgDIC+FJIF8AAIC9lIIi+lKIl7AAgEhwXAgDIC/FJIF8AAIC9lIIi/lKIl6AAgEiC4AgDIC+FJIF8AAIC+lIIi/lKIl7AAgEiVZAgDIC+FJIF8AAIC9lIIi+lKIl7AAgECScAf5IC+lJIi+lJIl8AAIi+FIIC/FKgEB/7Af5IC+lJIi+lJIl9AAIi9FIIC/FKgEBtZAf5IC+lJIi+lJIl8AAIi9FIIC/FKgEBa4Af5IC+lJIi+lJIl8AAIi+FIIC/FKgEBIXAf5IC9lJIi9lJIl9AAIi9FIIC/FKgEA11Af5IC+lJIi+lJIl8AAIi9FIIC+FKgEAjUAf5IC+lJIi+lJIl9AAIi9FIIC/FKgAQzf5IC9lJIi9lJIl9AAIi9FIIC/FKgAhsf5IDAlNIi7lFIl8AAIi+FIIC/FKgA0Jf5IC/lJIi/lJIl8AAIi9FIIC/FKgEgmqAf5IC/lJIi/lJIl8AAIi9FIIC/FKgEg5LAf5IC+lJIi+lJIl8AAIi9FIIC+FKgEhLsAf5IC+lJIi+lJIl8AAIi+FIIC/FKgEheOAf5IC/lJIi/lJIl8AAIi9FIIC/FKgEhwvAf5IC+lJIi+lJIl8AAIi+FIIC/FKgEiDQAf5IC+lJIi+lJIl8AAIi+FIIC/FKgECJPAaiIC9lJIjClQIl5AAIjDFQIC+FJgEB2tAaiIC+lJIjClQIl6AAIjCFQIC+FJgEBkMAaiIC+lJIjDlQIl5AAIjDFQIC+FJgEBRqAaiIC+lJIjClQIl6AAIjCFQIC+FJgEA/JAaiIC+lJIjDlQIl5AAIjCFQIC9FJgEAsoAaiIC+lJIjDlQIl5AAIjDFQIC+FJgAaGaiIC+lJIjClQIl6AAIjCFQIC+FJgAHlaiIC+lJIjDlQIlyAAIjBFQIC8FJgAq0aiIC9lJIjClQIl6AAIjCFQIC+FJgA9WaiIC+lJIjClQIl6AAIjCFQIC+FJgEgv3AaiIC+lJIjClQIl6AAIjCFQIC9FJgEhCYAaiIC9lJIjClQIl6AAIjCFQIC+FJgEhU6AaiIC+lJIjClQIl6AAIjCFQIC+FJgEhnbAaiIC+lJIjClQIl6AAIjCFQIC9FJgEh58AaiIC9lJIjClQIl6AAIjCFQIC+FJgECJiAQDIC+FJIF8AAIC+lJIi+lJIl8AAgEB3BAQDIC9FJIF9AAIC+lJIi+lJIl9AAgEBkfAQDIC+FJIF8AAIC+lJIi+lJIl8AAgEBR+AQDIC+FJIF8AAIC+lJIi+lJIl8AAgEA/cAQDIC+FJIF9AAIC9lJIi9lJIl9AAgEAs7AQDIC+FJIF8AAIC+lJIi+lJIl8AAgAaaQDIC9FJIF9AAIC+lJIi+lJIl9AAgAH4QDIC+FJIF9AAIC9lJIi9lJIl9AAgAqhQDIC+FJIF8AAIC9lJIi9lJIl8AAgA9DQDIC+FJIF8AAIC/lJIi/lJIl8AAgEgvkAQDIC+FJIF8AAIC/lJIi/lJIl8AAgEhCFAQDIC+FJIF8AAIC+lJIi+lJIl8AAgEhUnAQDIC/FJIF8AAIC+lJIi+lJIl8AAgEhnIAQDIC+FJIF8AAIC/lJIi/lJIl8AAgEh5pAQDIC+FJIF8AAIC+lJIi+lJIl8AAgEiMLAQDIC/FJIF8AAIC+lJIi+lJIl8AAgECATAKoIC+FKIF8AAIC+lJIi/lKIl7AAgEBtyAKoIC+FKIF8AAIC9lJIi/lKIl6AAgEBbQAKoIC+FKIF9AAIC9lJIi/lKIl7AAgEBIvAKoIC+FKIF8AAIC+lJIi/lKIl7AAgEA2OAKoIC+FKIF8AAIC9lJIi/lKIl6AAgEAjsAKoIC+FKIF9AAIC9lJIi/lKIl7AAgARLKoIC+FKIF8AAIC9lJIi+lKIl7AAgABnPyIF9AAIC9lJIi/lKIl2AAIi/FNgAzwKoIC+FKIF8AAIC+lIIi/lLIl7AAgEgmRAKoIC+FKIF8AAIC9lIIi/lLIl6AAgEg4yAKoIC+FKIF8AAIC9lIIi+lLIl7AAgEhLUAKoIC+FKIF8AAIC+lIIi/lLIl7AAgEhd1AKoIC+FKIF8AAIC9lIIi+lLIl7AAgEhwXAKoIC/FKIF8AAIC9lIIi/lLIl6AAgEiC4AKoIC+FKIF8AAIC+lIIi/lLIl7AAgEiVZAKoIC+FKIF8AAIC9lIIi+lLIl7AAgECScAKfIC+lJIi+lKIl8AAIi+FJIC/FKgEB/7AKfIC+lJIi+lKIl9AAIi9FJIC/FKgEBtZAKfIC+lJIi+lKIl8AAIi9FJIC/FKgEBa4AKfIC+lJIi+lKIl8AAIi+FJIC/FKgEBIXAKfIC9lJIi9lKIl9AAIi9FJIC/FKgEA11AKfIC+lJIi+lKIl8AAIi9FJIC+FKgEAjUAKfIC+lJIi+lKIl9AAIi9FJIC/FKgAQzKfIC9lJIi9lKIl9AAIi9FJIC/FKgAhsKfIDAlNIi7lGIl8AAIi+FIIC/FLgA0JKfIC/lJIi/lKIl8AAIi9FIIC/FLgEgmqAKfIC/lJIi/lKIl8AAIi9FIIC/FLgEg5LAKfIC+lJIi+lKIl8AAIi9FIIC+FLgEhLsAKfIC+lJIi+lKIl8AAIi+FIIC/FLgEheOAKfIC/lJIi/lKIl8AAIi9FIIC/FLgEhwvAKfIC+lJIi+lKIl8AAIi+FIIC/FLgEiDQAKfIC+lJIi+lKIl8AAIi+FIIC/FLgECJPAFHIC9lHIjClPIl5AAIjCFPIC9FHgEB2tAFHIC+lHIjClPIl6AAIjCFPIC+FHgEBkMAFHIC9lHIjClPIl5AAIjCFPIC9FHgEBRqAFHIC+lHIjClPIl6AAIjCFPIC+FHgEA/JAFHIC9lHIjClPIl5AAIjCFPIC9FHgEAsoAFHIC9lHIjClPIl5AAIjCFPIC9FHgAaGFHIC+lHIjClPIl6AAIjCFPIC+FHgAHlFHIC9lHIjClPIlyAAIjBFPIC8FHgAq0FHIC9lHIjClPIl6AAIjBFPIC9FHgA9WFHIC9lHIjBlPIl6AAIjBFPIC9FHgEgv3AFHIC9lHIjBlPIl6AAIjCFPIC9FHgEhCYAFHIC9lHIjClPIl6AAIjBFPIC9FHgEhU6AFHIC+lHIjClPIl6AAIjCFPIC+FHgEhnbAFHIC9lHIjBlPIl6AAIjCFPIC9FHgEh58AFHIC9lHIjClPIl6AAIjBFPIC9FHgECJigFVIC+FJIF8AAIC+lJIi+lJIl8AAgEB3BgFVIC9FJIF9AAIC+lJIi+lJIl9AAgEBkfgFVIC+FJIF8AAIC+lJIi+lJIl8AAgEBR+gFVIC+FJIF8AAIC+lJIi+lJIl8AAgEA/cgFVIC+FJIF9AAIC9lJIi9lJIl9AAgEAs7gFVIC+FJIF8AAIC+lJIi+lJIl8AAgAaalVIC9FJIF9AAIC+lJIi+lJIl9AAgAH4lVIC+FJIF9AAIC9lJIi9lJIl9AAgAqhlVIC+FJIF8AAIC9lJIi9lJIl8AAgA9DlVIC+FJIF8AAIC/lJIi/lJIl8AAgEgvkgFVIC+FJIF8AAIC/lJIi/lJIl8AAgEhCFgFVIC+FJIF8AAIC+lJIi+lJIl8AAgEhUngFVIC/FJIF8AAIC+lJIi+lJIl8AAgEhnIgFVIC+FJIF8AAIC/lJIi/lJIl8AAgEh5pgFVIC+FJIF8AAIC+lJIi+lJIl8AAgEiMLgFVIC/FJIF8AAIC+lJIi+lJIl8AAgECATgKwIC+FKIF8AAIC+lJIi/lKIl7AAgEBtygKwIC+FKIF8AAIC9lJIi/lKIl6AAgEBbQgKwIC+FKIF9AAIC9lJIi/lKIl7AAgEBIvgKwIC+FKIF8AAIC+lJIi/lKIl7AAgEA2OgKwIC+FKIF8AAIC9lJIi/lKIl6AAgEAjsgKwIC+FKIF9AAIC9lJIi/lKIl7AAgARLqwIC+FKIF8AAIC9lJIi+lKIl7AAgABnlmIF9AAIC9lJIi/lKIl2AAIi/FNgAzwqwIC+FKIF8AAIC+lIIi/lLIl7AAgEgmRgKwIC+FKIF8AAIC9lIIi/lLIl6AAgEg4ygKwIC+FKIF8AAIC9lIIi+lLIl7AAgEhLUgKwIC+FKIF8AAIC+lIIi/lLIl7AAgEhd1gKwIC+FKIF8AAIC9lIIi+lLIl7AAgEhwXgKwIC/FKIF8AAIC9lIIi/lLIl6AAgEiC4gKwIC+FKIF8AAIC+lIIi/lLIl7AAgEiVZgKwIC+FKIF8AAIC9lIIi+lLIl7AAgECScgK5IC+lJIi+lJIl8AAIi+FIIC/FKgEB/7gK5IC+lJIi+lJIl9AAIi9FIIC/FKgEBtZgK5IC+lJIi+lJIl8AAIi9FIIC/FKgEBa4gK5IC+lJIi+lJIl8AAIi+FIIC/FKgEBIXgK5IC9lJIi9lJIl9AAIi9FIIC/FKgEA11gK5IC+lJIi+lJIl8AAIi9FIIC+FKgEAjUgK5IC+lJIi+lJIl9AAIi9FIIC/FKgAQzq5IC9lJIi9lJIl9AAIi9FIIC/FKgAhsq5IDAlNIi7lFIl8AAIi+FHIC/FLgA0Jq5IC/lJIi/lJIl8AAIi9FHIC/FLgEgmqgK5IC/lJIi/lJIl8AAIi9FHIC/FLgEg5LgK5IC+lJIi+lJIl8AAIi9FHIC+FLgEhLsgK5IC+lJIi+lJIl8AAIi+FHIC/FLgEheOgK5IC/lJIi/lJIl8AAIi9FHIC/FLgEhwvgK5IC+lJIi+lJIl8AAIi+FHIC/FLgEiDQgK5IC+lJIi+lJIl8AAIi+FHIC/FLgECJPgQQIC9lJIjClQIl5AAIjDFQIC+FJgEB2tgQQIC+lJIjClQIl6AAIjCFQIC+FJgEBkMgQQIC+lJIjDlQIl5AAIjDFQIC+FJgEBRqgQQIC+lJIjClQIl6AAIjCFQIC+FJgEA/JgQQIC+lJIjDlQIl5AAIjCFQIC9FJgEAsogQQIC+lJIjDlQIl5AAIjDFQIC+FJgAaGwQIC+lJIjClQIl6AAIjCFQIC+FJgAHlwQIC+lJIjDlQIlyAAIjBFQIC8FJgAq0wQIC9lJIjClQIl6AAIjCFQIC+FJgA9WwQIC+lJIjClQIl6AAIjCFQIC+FJgEgv3gQQIC+lJIjClQIl6AAIjCFQIC9FJgEhCYgQQIC9lJIjClQIl6AAIjCFQIC+FJgEhU6gQQIC+lJIjClQIl6AAIjCFQIC+FJgEhnbgQQIC+lJIjClQIl6AAIjCFQIC9FJgEh58gQQIC9lJIjClQIl6AAIjCFQIC+FJgECJigawIC+FKIF8AAIC+lKIi+lJIl8AAgEB3BgawIC9FKIF9AAIC+lKIi+lJIl9AAgEBkfgawIC+FKIF8AAIC+lKIi+lJIl8AAgEBR+gawIC+FKIF8AAIC+lKIi+lJIl8AAgEA/cgawIC+FKIF9AAIC9lKIi9lJIl9AAgEAs7gawIC+FKIF8AAIC+lKIi+lJIl8AAgAaa6wIC9FKIF9AAIC+lKIi+lJIl9AAgAH46wIC+FKIF9AAIC9lKIi9lJIl9AAgAqh6wIC+FKIF8AAIC9lKIi9lJIl8AAgA9D6wIC+FKIF8AAIC/lKIi/lJIl8AAgEgvkgawIC+FKIF8AAIC/lKIi/lJIl8AAgEhCFgawIC+FKIF8AAIC+lKIi+lJIl8AAgEhUngawIC/FKIF8AAIC+lKIi+lJIl8AAgEhnIgawIC+FKIF8AAIC/lKIi/lJIl8AAgEh5pgawIC+FKIF8AAIC+lKIi+lJIl8AAgEiMLgawIC/FKIF8AAIC+lKIi+lJIl8AAgECATggKIC+FJIF8AAIC+lIIi/lKIl7AAgEBtyggKIC+FJIF8AAIC9lIIi/lKIl6AAgEBbQggKIC+FJIF9AAIC9lIIi/lKIl7AAgEBIvggKIC+FJIF8AAIC+lIIi/lKIl7AAgEA2OggKIC+FJIF8AAIC9lIIi/lKIl6AAgEAjsggKIC+FJIF9AAIC9lIIi/lKIl7AAgEARLggKIC+FJIF8AAIC9lIIi+lKIl7AAgABn7BIF9AAIC9lIIi/lKIl2AAIi/FNgEgTwggKIC+FJIF8AAIC+lIIi/lKIl7AAgEgmRggKIC+FJIF8AAIC9lIIi/lKIl6AAgEg4yggKIC+FJIF8AAIC9lIIi+lKIl7AAgEhLUggKIC+FJIF8AAIC+lIIi/lKIl7AAgEhd1ggKIC+FJIF8AAIC9lIIi+lKIl7AAgEhwXggKIC/FJIF8AAIC9lIIi/lKIl6AAgEiC4ggKIC+FJIF8AAIC+lIIi/lKIl7AAgEiVZggKIC+FJIF8AAIC9lIIi+lKIl7AAgECScggUIC+lJIi+lJIl8AAIi+FIIC/FKgEB/7ggUIC+lJIi+lJIl9AAIi9FIIC/FKgEBtZggUIC+lJIi+lJIl8AAIi9FIIC/FKgEBa4ggUIC+lJIi+lJIl8AAIi+FIIC/FKgEBIXggUIC9lJIi9lJIl9AAIi9FIIC/FKgEA11ggUIC+lJIi+lJIl8AAIi9FIIC+FKgEAjUggUIC+lJIi+lJIl9AAIi9FIIC/FKgEAQzggUIC9lJIi9lJIl9AAIi9FIIC/FKgEgBsggUIDAlMIi7lGIl8AAIi+FIIC/FKgEgUJggUIC/lJIi/lJIl8AAIi9FIIC/FKgEgmqggUIC/lJIi/lJIl8AAIi9FIIC/FKgEg5LggUIC+lJIi+lJIl8AAIi9FIIC+FKgEhLsggUIC+lJIi+lJIl8AAIi+FIIC/FKgEheOggUIC/lJIi/lJIl8AAIi9FIIC/FKgEhwvggUIC+lJIi+lJIl8AAIi+FIIC/FKgEiDQggUIC+lJIi+lJIl8AAIi+FIIC/FKgECJPglrIC9lIIjClRIl5AAIjDFRIC+FIgEB2tglrIC+lIIjClRIl6AAIjCFRIC+FIgEBkMglrIC+lIIjDlRIl5AAIjDFRIC+FIgEBRqglrIC+lIIjClRIl6AAIjCFRIC+FIgEA/JglrIC+lIIjDlRIl5AAIjCFRIC9FIgEAsoglrIC+lIIjDlRIl5AAIjDFRIC+FIgEAaGglrIC+lIIjClRIl6AAIjCFRIC+FIgEAHlglrIC+lIIjDlRIlyAAIjBFRIC8FIgEgK0glrIC9lIIjClRIl6AAIjCFRIC+FIgEgdWglrIC+lIIjClRIl6AAIjCFRIC+FIgEgv3glrIC+lIIjClRIl6AAIjCFRIC9FIgEhCYglrIC9lIIjClRIl6AAIjCFRIC+FIgEhU6glrIC+lIIjClRIl6AAIjCFRIC+FIgEhnbglrIC+lIIjClRIl6AAIjCFRIC9FIgEh58glrIC9lIIjClRIl6AAIjCFRIC+FIgECJigwKIC+FJIF8AAIC+lJIi+lJIl8AAgEB3BgwKIC9FJIF9AAIC+lJIi+lJIl9AAgEBkfgwKIC+FJIF8AAIC+lJIi+lJIl8AAgEBR+gwKIC+FJIF8AAIC+lJIi+lJIl8AAgEA/cgwKIC+FJIF9AAIC9lJIi9lJIl9AAgEAs7gwKIC+FJIF8AAIC+lJIi+lJIl8AAgEAaagwKIC9FJIF9AAIC+lJIi+lJIl9AAgEAH4gwKIC+FJIF9AAIC9lJIi9lJIl9AAgEgKhgwKIC+FJIF8AAIC9lJIi9lJIl8AAgEgdDgwKIC+FJIF8AAIC/lJIi/lJIl8AAgEgvkgwKIC+FJIF8AAIC/lJIi/lJIl8AAgEhCFgwKIC+FJIF8AAIC+lJIi+lJIl8AAgEhUngwKIC/FJIF8AAIC+lJIi+lJIl8AAgEhnIgwKIC+FJIF8AAIC/lJIi/lJIl8AAgEh5pgwKIC+FJIF8AAIC+lJIi+lJIl8AAgEiMLgwKIC/FJIF8AAIC+lJIi+lJIl8AAgECATg1lIC+FKIF8AAIC+lJIi/lKIl7AAgEBtyg1lIC+FKIF8AAIC9lJIi/lKIl6AAgEBbQg1lIC+FKIF9AAIC9lJIi/lKIl7AAgEBIvg1lIC+FKIF8AAIC+lJIi/lKIl7AAgEA2Og1lIC+FKIF8AAIC9lJIi/lKIl6AAgEAjsg1lIC+FKIF9AAIC9lJIi/lKIl7AAgEARLg1lIC+FKIF8AAIC9lJIi+lKIl7AAgEABngwbIF9AAIC9lJIi/lKIl2AAIi/FNgEgTwg1lIC+FKIF8AAIC+lIIi/lLIl7AAgEgmRg1lIC+FKIF8AAIC9lIIi/lLIl6AAgEg4yg1lIC+FKIF8AAIC9lIIi+lLIl7AAgEhLUg1lIC+FKIF8AAIC+lIIi/lLIl7AAgEhd1g1lIC+FKIF8AAIC9lIIi+lLIl7AAgEhwXg1lIC/FKIF8AAIC9lIIi/lLIl6AAgEiC4g1lIC+FKIF8AAIC+lIIi/lLIl7AAgEiVZg1lIC+FKIF8AAIC9lIIi+lLIl7AAgECScg1uIC+lJIi+lJIl8AAIi+FIIC/FKgEB/7g1uIC+lJIi+lJIl9AAIi9FIIC/FKgEBtZg1uIC+lJIi+lJIl8AAIi9FIIC/FKgEBa4g1uIC+lJIi+lJIl8AAIi+FIIC/FKgEBIXg1uIC9lJIi9lJIl9AAIi9FIIC/FKgEA11g1uIC+lJIi+lJIl8AAIi9FIIC+FKgEAjUg1uIC+lJIi+lJIl9AAIi9FIIC/FKgEAQzg1uIC9lJIi9lJIl9AAIi9FIIC/FKgEgBsg1uIDAlNIi7lFIl8AAIi+FIIC/FKgEgUJg1uIC/lJIi/lJIl8AAIi9FIIC/FKgEgmqg1uIC/lJIi/lJIl8AAIi9FIIC/FKgEg5Lg1uIC+lJIi+lJIl8AAIi9FIIC+FKgEhLsg1uIC+lJIi+lJIl8AAIi+FIIC/FKgEheOg1uIC/lJIi/lJIl8AAIi9FIIC/FKgEhwvg1uIC+lJIi+lJIl8AAIi+FIIC/FKgEiDQg1uIC+lJIi+lJIl8AAIi+FIIC/FKgECJPg7FIC9lJIjClQIl5AAIjDFQIC+FJgEB2tg7FIC+lJIjClQIl6AAIjCFQIC+FJgEBkMg7FIC+lJIjDlQIl5AAIjDFQIC+FJgEBRqg7FIC+lJIjClQIl6AAIjCFQIC+FJgEA/Jg7FIC+lJIjDlQIl5AAIjCFQIC9FJgEAsog7FIC9lJIjClQIl5AAIjDFQIC+FJgEAaGg7FIC+lJIjClQIl6AAIjCFQIC+FJgEAHlg7FIC+lJIjDlQIlyAAIjBFQIC8FJgEgK0g7FIC9lJIjClQIl6AAIjCFQIC+FJgEgdWg7FIC+lJIjClQIl6AAIjCFQIC+FJgEgv3g7FIC+lJIjClQIl6AAIjCFQIC9FJgEhCYg7FIC9lJIjClQIl6AAIjBFQIC9FJgEhU6g7FIC+lJIjClQIl6AAIjCFQIC+FJgEhnbg7FIC9lJIjBlQIl6AAIjCFQIC9FJgEh58g7FIC9lJIjClQIl6AAIjCFQIC+FJgECJihFkIC+FJIF8AAIC+lJIi+lJIl8AAgEB3BhFkIC9FJIF9AAIC+lJIi+lJIl9AAgEBkfhFkIC+FJIF8AAIC+lJIi+lJIl8AAgEBR+hFkIC+FJIF8AAIC+lJIi+lJIl8AAgEA/chFkIC+FJIF9AAIC9lJIi9lJIl9AAgEAs7hFkIC+FJIF8AAIC+lJIi+lJIl8AAgEAaahFkIC9FJIF9AAIC+lJIi+lJIl9AAgEAH4hFkIC+FJIF9AAIC9lJIi9lJIl9AAgEgKhhFkIC+FJIF8AAIC9lJIi9lJIl8AAgEgdDhFkIC+FJIF8AAIC/lJIi/lJIl8AAgEgvkhFkIC+FJIF8AAIC/lJIi/lJIl8AAgEhCFhFkIC+FJIF8AAIC+lJIi+lJIl8AAgEhUnhFkIC/FJIF8AAIC+lJIi+lJIl8AAgEhnIhFkIC+FJIF8AAIC/lJIi/lJIl8AAgEh5phFkIC+FJIF8AAIC+lJIi+lJIl8AAgEiMLhFkIC/FJIF8AAIC+lJIi+lJIl8AAgECAThK/IC+FKIF8AAIC+lJIi/lKIl7AAgEBtyhK/IC+FKIF8AAIC9lJIi/lKIl6AAgEBbQhK/IC+FKIF9AAIC9lJIi/lKIl7AAgEBIvhK/IC+FKIF8AAIC+lJIi/lKIl7AAgEA2OhK/IC+FKIF8AAIC9lJIi/lKIl6AAgEAjshK/IC+FKIF9AAIC9lJIi/lKIl7AAgEARLhK/IC+FKIF8AAIC9lJIi+lKIl7AAgEABnhF1IF9AAIC9lJIi/lKIl2AAIi/FNgEgTwhK/IC+FKIF8AAIC+lIIi/lLIl7AAgEgmRhK/IC+FKIF8AAIC9lIIi/lLIl6AAgEg4yhK/IC+FKIF8AAIC9lIIi+lLIl7AAgEhLUhK/IC+FKIF8AAIC+lIIi/lLIl7AAgEhd1hK/IC+FKIF8AAIC9lIIi+lLIl7AAgEhwXhK/IC/FKIF8AAIC9lIIi/lLIl6AAgEiC4hK/IC+FKIF8AAIC+lIIi/lLIl7AAgEiVZhK/IC+FKIF8AAIC9lIIi+lLIl7AAgECSchLIIC+lJIi+lKIl8AAIi+FJIC/FKgEB/7hLIIC+lJIi+lKIl9AAIi9FJIC/FKgEBtZhLIIC+lJIi+lKIl8AAIi9FJIC/FKgEBa4hLIIC+lJIi+lKIl8AAIi+FJIC/FKgEBIXhLIIC9lJIi9lKIl9AAIi9FJIC/FKgEA11hLIIC+lJIi+lKIl8AAIi9FJIC+FKgEAjUhLIIC+lJIi+lKIl9AAIi9FJIC/FKgEAQzhLIIC9lJIi9lKIl9AAIi9FJIC/FKgEgBshLIIDAlNIi7lGIl8AAIi+FIIC/FLgEgUJhLIIC/lJIi/lKIl8AAIi9FIIC/FLgEgmqhLIIC/lJIi/lKIl8AAIi9FIIC/FLgEg5LhLIIC+lJIi+lKIl8AAIi9FIIC+FLgEhLshLIIC+lJIi+lKIl8AAIi+FIIC/FLgEheOhLIIC/lJIi/lKIl8AAIi9FIIC/FLgEhwvhLIIC+lJIi+lKIl8AAIi+FIIC/FLgEiDQhLIIC+lJIi+lKIl8AAIi+FIIC/FLgECJPhQfIC9lJIjClQIl5AAIjDFQIC+FJgEB2thQfIC+lJIjClQIl6AAIjCFQIC+FJgEBkMhQfIC+lJIjDlQIl5AAIjDFQIC+FJgEBRqhQfIC+lJIjClQIl6AAIjCFQIC+FJgEA/JhQfIC+lJIjDlQIl5AAIjCFQIC9FJgEAsohQfIC+lJIjDlQIl5AAIjDFQIC+FJgEAaGhQfIC+lJIjClQIl6AAIjCFQIC+FJgEAHlhQfIC+lJIjDlQIlyAAIjBFQIC8FJgEgK0hQfIC9lJIjClQIl6AAIjCFQIC+FJgEgdWhQfIC+lJIjClQIl6AAIjCFQIC+FJgEgv3hQfIC+lJIjClQIl6AAIjCFQIC9FJgEhCYhQfIC9lJIjClQIl6AAIjCFQIC+FJgEhU6hQfIC+lJIjClQIl6AAIjCFQIC+FJgEhnbhQfIC+lJIjClQIl6AAIjCFQIC9FJgEh58hQfIC9lJIjClQIl6AAIjCFQIC+FJgECJiha/IC+FKIF8AAIC+lKIi+lJIl8AAgEB3Bha/IC9FKIF9AAIC+lKIi+lJIl9AAgEBkfha/IC+FKIF8AAIC+lKIi+lJIl8AAgEBR+ha/IC+FKIF8AAIC+lKIi+lJIl8AAgEA/cha/IC+FKIF9AAIC9lKIi9lJIl9AAgEAs7ha/IC+FKIF8AAIC+lKIi+lJIl8AAgEAaaha/IC9FKIF9AAIC+lKIi+lJIl9AAgEAH4ha/IC+FKIF9AAIC9lKIi9lJIl9AAgEgKhha/IC+FKIF8AAIC9lKIi9lJIl8AAgEgdDha/IC+FKIF8AAIC/lKIi/lJIl8AAgEgvkha/IC+FKIF8AAIC/lKIi/lJIl8AAgEhCFha/IC+FKIF8AAIC+lKIi+lJIl8AAgEhUnha/IC/FKIF8AAIC+lKIi+lJIl8AAgEhnIha/IC+FKIF8AAIC/lKIi/lJIl8AAgEh5pha/IC+FKIF8AAIC+lKIi+lJIl8AAgEiMLha/IC/FKIF8AAIC+lKIi+lJIl8AAgECAThgZIC+FJIF8AAIC+lIIi/lKIl7AAgEBtyhgZIC+FJIF8AAIC9lIIi/lKIl6AAgEBbQhgZIC+FJIF9AAIC9lIIi/lKIl7AAgEBIvhgZIC+FJIF8AAIC+lIIi/lKIl7AAgEA2OhgZIC+FJIF8AAIC9lIIi/lKIl6AAgEAjshgZIC+FJIF9AAIC9lIIi/lKIl7AAgEARLhgZIC+FJIF8AAIC9lIIi+lKIl7AAgEABnhbQIF9AAIC9lIIi/lKIl2AAIi/FNgEgTwhgZIC+FJIF8AAIC+lIIi/lKIl7AAgEgmRhgZIC+FJIF8AAIC9lIIi/lKIl6AAgEg4yhgZIC+FJIF8AAIC9lIIi+lKIl7AAgEhLUhgZIC+FJIF8AAIC+lIIi/lKIl7AAgEhd1hgZIC+FJIF8AAIC9lIIi+lKIl7AAgEhwXhgZIC/FJIF8AAIC9lIIi/lKIl6AAgEiC4hgZIC+FJIF8AAIC+lIIi/lKIl7AAgEiVZhgZIC+FJIF8AAIC9lIIi+lKIl7AAgECSchgjIC+lJIi+lJIl8AAIi+FIIC/FKgEB/7hgjIC+lJIi+lJIl9AAIi9FIIC/FKgEBtZhgjIC+lJIi+lJIl8AAIi9FIIC/FKgEBa4hgjIC+lJIi+lJIl8AAIi+FIIC/FKgEBIXhgjIC9lJIi9lJIl9AAIi9FIIC/FKgEA11hgjIC+lJIi+lJIl8AAIi9FIIC+FKgEAjUhgjIC+lJIi+lJIl9AAIi9FIIC/FKgEAQzhgjIC9lJIi9lJIl9AAIi9FIIC/FKgEgBshgjIDAlMIi7lGIl8AAIi+FIIC/FKgEgUJhgjIC/lJIi/lJIl8AAIi9FIIC/FKgEgmqhgjIC/lJIi/lJIl8AAIi9FIIC/FKgEg5LhgjIC+lJIi+lJIl8AAIi9FIIC+FKgEhLshgjIC+lJIi+lJIl8AAIi+FIIC/FKgEheOhgjIC/lJIi/lJIl8AAIi9FIIC/FKgEhwvhgjIC+lJIi+lJIl8AAIi+FIIC/FKgEiDQhgjIC+lJIi+lJIl8AAIi+FIIC/FKgECJPhl6IC9lIIjClRIl5AAIjDFRIC+FIgEB2thl6IC+lIIjClRIl6AAIjCFRIC+FIgEBkMhl6IC+lIIjDlRIl5AAIjDFRIC+FIgEBRqhl6IC+lIIjClRIl6AAIjCFRIC+FIgEA/Jhl6IC+lIIjDlRIl5AAIjCFRIC9FIgEAsohl6IC+lIIjDlRIl5AAIjDFRIC+FIgEAaGhl6IC+lIIjClRIl6AAIjCFRIC+FIgEAHlhl6IC+lIIjDlRIlyAAIjBFRIC8FIgEgK0hl6IC9lIIjClRIl6AAIjCFRIC+FIgEgdWhl6IC+lIIjClRIl6AAIjCFRIC+FIgEgv3hl6IC+lIIjClRIl6AAIjCFRIC9FIgEhCYhl6IC9lIIjClRIl6AAIjCFRIC+FIgEhU6hl6IC+lIIjClRIl6AAIjCFRIC+FIgEhnbhl6IC+lIIjClRIl6AAIjCFRIC9FIgEh58hl6IC9lIIjClRIl6AAIjCFRIC+FIgECJihwZIC+FJIF8AAIC+lJIi+lJIl8AAgEB3BhwZIC9FJIF9AAIC+lJIi+lJIl9AAgEBkfhwZIC+FJIF8AAIC+lJIi+lJIl8AAgEBR+hwZIC+FJIF8AAIC+lJIi+lJIl8AAgEA/chwZIC+FJIF9AAIC9lJIi9lJIl9AAgEAs7hwZIC+FJIF8AAIC+lJIi+lJIl8AAgEAaahwZIC9FJIF9AAIC+lJIi+lJIl9AAgEAH4hwZIC+FJIF9AAIC9lJIi9lJIl9AAgEgKhhwZIC+FJIF8AAIC9lJIi9lJIl8AAgEgdDhwZIC+FJIF8AAIC/lJIi/lJIl8AAgEgvkhwZIC+FJIF8AAIC/lJIi/lJIl8AAgEhCFhwZIC+FJIF8AAIC+lJIi+lJIl8AAgEhUnhwZIC/FJIF8AAIC+lJIi+lJIl8AAgEhnIhwZIC+FJIF8AAIC/lJIi/lJIl8AAgEh5phwZIC+FJIF8AAIC+lJIi+lJIl8AAgEiMLhwZIC/FJIF8AAIC+lJIi+lJIl8AAgECATh10IC+FKIF8AAIC+lJIi/lKIl7AAgEBtyh10IC+FKIF8AAIC9lJIi/lKIl6AAgEBbQh10IC+FKIF9AAIC9lJIi/lKIl7AAgEBIvh10IC+FKIF8AAIC+lJIi/lKIl7AAgEA2Oh10IC+FKIF8AAIC9lJIi/lKIl6AAgEAjsh10IC+FKIF9AAIC9lJIi/lKIl7AAgEARLh10IC+FKIF8AAIC9lJIi+lKIl7AAgEABnhwqIF9AAIC9lJIi/lKIl2AAIi/FNgEgTwh10IC+FKIF8AAIC+lIIi/lLIl7AAgEgmRh10IC+FKIF8AAIC9lIIi/lLIl6AAgEg4yh10IC+FKIF8AAIC9lIIi+lLIl7AAgEhLUh10IC+FKIF8AAIC+lIIi/lLIl7AAgEhd1h10IC+FKIF8AAIC9lIIi+lLIl7AAgEhwXh10IC/FKIF8AAIC9lIIi/lLIl6AAgEiC4h10IC+FKIF8AAIC+lIIi/lLIl7AAgEiVZh10IC+FKIF8AAIC9lIIi+lLIl7AAgECSch19IC+lJIi+lJIl8AAIi+FIIC/FKgEB/7h19IC+lJIi+lJIl9AAIi9FIIC/FKgEBtZh19IC+lJIi+lJIl8AAIi9FIIC/FKgEBa4h19IC+lJIi+lJIl8AAIi+FIIC/FKgEBIXh19IC9lJIi9lJIl9AAIi9FIIC/FKgEA11h19IC+lJIi+lJIl8AAIi9FIIC+FKgEAjUh19IC+lJIi+lJIl9AAIi9FIIC/FKgEAQzh19IC9lJIi9lJIl9AAIi9FIIC/FKgEgBsh19IDAlNIi7lFIl8AAIi+FHIC/FLgEgUJh19IC/lJIi/lJIl8AAIi9FHIC/FLgEgmqh19IC/lJIi/lJIl8AAIi9FHIC/FLgEg5Lh19IC+lJIi+lJIl8AAIi9FHIC+FLgEhLsh19IC+lJIi+lJIl8AAIi+FHIC/FLgEheOh19IC/lJIi/lJIl8AAIi9FHIC/FLgEhwvh19IC+lJIi+lJIl8AAIi+FHIC/FLgEiDQh19IC+lJIi+lJIl8AAIi+FHIC/FLg");
	mask.setTransform(658.4571,383.1093);

	// light_purple
	this.instance = new lib.lightpurple();
	this.instance.setTransform(1269.35,874.35,1,1.4262,44.9983);
	this.instance.alpha = 0.3008;

	var maskedShapeInstanceList = [this.instance];

	for(var shapedInstanceItr = 0; shapedInstanceItr < maskedShapeInstanceList.length; shapedInstanceItr++) {
		maskedShapeInstanceList[shapedInstanceItr].mask = mask;
	}

	this.timeline.addTween(cjs.Tween.get(this.instance).to({x:-108.05,y:-141},56,cjs.Ease.get(-1)).wait(17));

	// Layer_16 (mask)
	var mask_1 = new cjs.Shape();
	mask_1._off = true;
	var mask_1_graphics_14 = new cjs.Graphics().p("Av7P8IAA/3If3AAIAAf3g");
	var mask_1_graphics_15 = new cjs.Graphics().p("A0JP8IAA/3MAoTAAAIAAf3g");
	var mask_1_graphics_16 = new cjs.Graphics().p("A4YP8IAA/3MAwwAAAIAAf3g");
	var mask_1_graphics_17 = new cjs.Graphics().p("A8mP8IAA/3MA5MAAAIAAf3g");
	var mask_1_graphics_18 = new cjs.Graphics().p("Egg0AP8IAA/3MBBoAAAIAAf3g");
	var mask_1_graphics_19 = new cjs.Graphics().p("EglCAP8IAA/3MBKFAAAIAAf3g");
	var mask_1_graphics_20 = new cjs.Graphics().p("EgpQAP8IAA/3MBShAAAIAAf3g");
	var mask_1_graphics_21 = new cjs.Graphics().p("EgteAP8IAA/3MBa9AAAIAAf3g");
	var mask_1_graphics_22 = new cjs.Graphics().p("EgxsAP8IAA/3MBjZAAAIAAf3g");
	var mask_1_graphics_23 = new cjs.Graphics().p("Eg16AP8IAA/3MBr1AAAIAAf3g");
	var mask_1_graphics_24 = new cjs.Graphics().p("Eg6IAP8IAA/3MB0SAAAIAAf3g");
	var mask_1_graphics_25 = new cjs.Graphics().p("Eg+WAP8IAA/3MB8uAAAIAAf3g");
	var mask_1_graphics_26 = new cjs.Graphics().p("EhCkAP8IAA/3MCFKAAAIAAf3g");
	var mask_1_graphics_27 = new cjs.Graphics().p("EhGyAP8IAA/3MCNmAAAIAAf3g");
	var mask_1_graphics_28 = new cjs.Graphics().p("EhLBAP8IAA/3MCWDAAAIAAf3g");
	var mask_1_graphics_29 = new cjs.Graphics().p("EhPPAP8IAA/3MCefAAAIAAf3g");
	var mask_1_graphics_30 = new cjs.Graphics().p("EhTdAP8IAA/3MCm7AAAIAAf3g");
	var mask_1_graphics_31 = new cjs.Graphics().p("EhXrAP8IAA/3MCvXAAAIAAf3g");
	var mask_1_graphics_32 = new cjs.Graphics().p("Ehb5AP8IAA/3MC3zAAAIAAf3g");
	var mask_1_graphics_33 = new cjs.Graphics().p("EhgIAP8IAA/3MDARAAAIAAf3g");
	var mask_1_graphics_34 = new cjs.Graphics().p("EhkWAP8IAA/3MDItAAAIAAf3g");

	this.timeline.addTween(cjs.Tween.get(mask_1).to({graphics:null,x:0,y:0}).wait(14).to({graphics:mask_1_graphics_14,x:474.125,y:554.175}).wait(1).to({graphics:mask_1_graphics_15,x:474.125,y:554.175}).wait(1).to({graphics:mask_1_graphics_16,x:474.15,y:554.175}).wait(1).to({graphics:mask_1_graphics_17,x:474.15,y:554.175}).wait(1).to({graphics:mask_1_graphics_18,x:474.15,y:554.175}).wait(1).to({graphics:mask_1_graphics_19,x:474.175,y:554.175}).wait(1).to({graphics:mask_1_graphics_20,x:474.15,y:554.175}).wait(1).to({graphics:mask_1_graphics_21,x:474.175,y:554.175}).wait(1).to({graphics:mask_1_graphics_22,x:474.175,y:554.175}).wait(1).to({graphics:mask_1_graphics_23,x:474.175,y:554.175}).wait(1).to({graphics:mask_1_graphics_24,x:474.2,y:554.175}).wait(1).to({graphics:mask_1_graphics_25,x:474.2,y:554.175}).wait(1).to({graphics:mask_1_graphics_26,x:474.2,y:554.175}).wait(1).to({graphics:mask_1_graphics_27,x:474.2,y:554.175}).wait(1).to({graphics:mask_1_graphics_28,x:474.225,y:554.175}).wait(1).to({graphics:mask_1_graphics_29,x:474.225,y:554.175}).wait(1).to({graphics:mask_1_graphics_30,x:474.225,y:554.175}).wait(1).to({graphics:mask_1_graphics_31,x:474.225,y:554.175}).wait(1).to({graphics:mask_1_graphics_32,x:474.225,y:554.175}).wait(1).to({graphics:mask_1_graphics_33,x:474.25,y:554.175}).wait(1).to({graphics:mask_1_graphics_34,x:474.25,y:554.175}).wait(39));

	// line01
	this.instance_1 = new lib.line01();
	this.instance_1.setTransform(96.8,531.15,0.6145,0.6145,0,0,0,0.1,0.1);
	this.instance_1._off = true;

	var maskedShapeInstanceList = [this.instance_1];

	for(var shapedInstanceItr = 0; shapedInstanceItr < maskedShapeInstanceList.length; shapedInstanceItr++) {
		maskedShapeInstanceList[shapedInstanceItr].mask = mask_1;
	}

	this.timeline.addTween(cjs.Tween.get(this.instance_1).wait(14).to({_off:false},0).wait(59));

	// Layer_15 (mask)
	var mask_2 = new cjs.Shape();
	mask_2._off = true;
	var mask_2_graphics_0 = new cjs.Graphics().p("EBEdAhJMAAAgk4MAk4AAAMAAAAk4g");
	var mask_2_graphics_1 = new cjs.Graphics().p("A3QScMAAAgk3MAuhAAAMAAAAk3g");
	var mask_2_graphics_2 = new cjs.Graphics().p("A8FScMAAAgk3MA4LAAAMAAAAk3g");
	var mask_2_graphics_3 = new cjs.Graphics().p("Egg6AScMAAAgk3MBB1AAAMAAAAk3g");
	var mask_2_graphics_4 = new cjs.Graphics().p("EglvAScMAAAgk3MBLfAAAMAAAAk3g");
	var mask_2_graphics_5 = new cjs.Graphics().p("EgqkAScMAAAgk3MBVJAAAMAAAAk3g");
	var mask_2_graphics_6 = new cjs.Graphics().p("EgvZAScMAAAgk3MBezAAAMAAAAk3g");
	var mask_2_graphics_7 = new cjs.Graphics().p("Eg0OAScMAAAgk3MBodAAAMAAAAk3g");
	var mask_2_graphics_8 = new cjs.Graphics().p("Eg5DAScMAAAgk3MByHAAAMAAAAk3g");
	var mask_2_graphics_9 = new cjs.Graphics().p("Eg94AScMAAAgk3MB7xAAAMAAAAk3g");
	var mask_2_graphics_10 = new cjs.Graphics().p("EhCtAScMAAAgk3MCFbAAAMAAAAk3g");
	var mask_2_graphics_11 = new cjs.Graphics().p("EhHiAScMAAAgk3MCPFAAAMAAAAk3g");
	var mask_2_graphics_12 = new cjs.Graphics().p("EhMXAScMAAAgk3MCYvAAAMAAAAk3g");
	var mask_2_graphics_13 = new cjs.Graphics().p("EhRMAScMAAAgk3MCiZAAAMAAAAk3g");
	var mask_2_graphics_14 = new cjs.Graphics().p("Egm3AhJMAAAgk4MCsEAAAMAAAAk4g");

	this.timeline.addTween(cjs.Tween.get(mask_2).to({graphics:mask_2_graphics_0,x:674.15,y:212.075}).wait(1).to({graphics:mask_2_graphics_1,x:1224.875,y:306.125}).wait(1).to({graphics:mask_2_graphics_2,x:1219.425,y:306.125}).wait(1).to({graphics:mask_2_graphics_3,x:1214.025,y:306.125}).wait(1).to({graphics:mask_2_graphics_4,x:1208.575,y:306.125}).wait(1).to({graphics:mask_2_graphics_5,x:1203.175,y:306.125}).wait(1).to({graphics:mask_2_graphics_6,x:1197.725,y:306.125}).wait(1).to({graphics:mask_2_graphics_7,x:1192.325,y:306.125}).wait(1).to({graphics:mask_2_graphics_8,x:1186.925,y:306.125}).wait(1).to({graphics:mask_2_graphics_9,x:1181.475,y:306.125}).wait(1).to({graphics:mask_2_graphics_10,x:1176.075,y:306.125}).wait(1).to({graphics:mask_2_graphics_11,x:1170.625,y:306.125}).wait(1).to({graphics:mask_2_graphics_12,x:1165.225,y:306.125}).wait(1).to({graphics:mask_2_graphics_13,x:1159.775,y:306.125}).wait(1).to({graphics:mask_2_graphics_14,x:852.5,y:212.075}).wait(59));

	// line02
	this.instance_2 = new lib.line02();
	this.instance_2.setTransform(882.15,329.1,0.7536,0.7536);

	var maskedShapeInstanceList = [this.instance_2];

	for(var shapedInstanceItr = 0; shapedInstanceItr < maskedShapeInstanceList.length; shapedInstanceItr++) {
		maskedShapeInstanceList[shapedInstanceItr].mask = mask_2;
	}

	this.timeline.addTween(cjs.Tween.get(this.instance_2).wait(73));

	// title
	this.instance_3 = new lib.tittle();
	this.instance_3.setTransform(544.35,419.05);
	this.instance_3.alpha = 0;
	this.instance_3._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_3).wait(6).to({_off:false},0).to({x:536.35,alpha:1},8,cjs.Ease.get(1)).wait(59));

	// B3
	this.instance_4 = new lib.B3_1();
	this.instance_4.setTransform(287.45,491.5,0.5,0.5,74.9998);
	this.instance_4.alpha = 0;
	this.instance_4._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_4).wait(19).to({_off:false},0).to({scaleX:1.5,scaleY:1.5,rotation:0,y:491.45,alpha:1},6).to({scaleX:1,scaleY:1,x:287.5,y:491.5},5).wait(43));

	// B2
	this.instance_5 = new lib.B2_1();
	this.instance_5.setTransform(671.5,243.05,0.5,0.5,74.9998,0,0,0.1,-0.1);
	this.instance_5.alpha = 0;
	this.instance_5._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_5).wait(13).to({_off:false},0).to({regX:0,regY:0,scaleX:1.5,scaleY:1.5,rotation:0,x:671.45,y:242.9,alpha:1},6).to({scaleX:1,scaleY:1,x:671.5,y:243},5).wait(49));

	// B1
	this.instance_6 = new lib.B1_1();
	this.instance_6.setTransform(353,434,0.1629,0.1629);
	this.instance_6.alpha = 0;
	this.instance_6._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_6).wait(13).to({_off:false},0).to({scaleX:1.1346,scaleY:1.1346,alpha:1},6).to({scaleX:1,scaleY:1},5).wait(49));

	// B1
	this.instance_7 = new lib.B1_1();
	this.instance_7.setTransform(753,354,0.1629,0.1629);
	this.instance_7.alpha = 0;
	this.instance_7._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_7).wait(9).to({_off:false},0).to({scaleX:1.1346,scaleY:1.1346,alpha:1},5).to({scaleX:1,scaleY:1},5).wait(54));

	// bg2
	this.instance_8 = new lib.bg2_2();
	this.instance_8.setTransform(540,404);

	this.timeline.addTween(cjs.Tween.get(this.instance_8).wait(73));

	// bg
	this.instance_9 = new lib.bg2_1("synched",0);
	this.instance_9.setTransform(605,451.35,1.322,1.322,0,0,0,539.9,399.9);

	this.timeline.addTween(cjs.Tween.get(this.instance_9).to({regX:539.8,regY:399.7,scaleX:1.2719,scaleY:1.2719,x:418.65,y:311.05,alpha:0},35,cjs.Ease.get(1)).wait(38));

	// bg
	this.instance_10 = new lib.bg2_1("synched",0);
	this.instance_10.setTransform(150,125,1,1,0,0,0,150,125);

	this.timeline.addTween(cjs.Tween.get(this.instance_10).wait(73));

	this._renderFirstFrame();

}).prototype = p = new lib.AnMovieClip();
p.nominalBounds = new cjs.Rectangle(239.5,-40.1,1378,1246.5);
// library properties:
lib.properties = {
	id: 'FB59D1E0A848436885A0B7989A76664A',
	width: 1080,
	height: 800,
	fps: 24,
	color: "#333333",
	opacity: 1.00,
	manifest: [
		{src:"images/banner/gum/images/B1.png?1614313836459", id:"B1"},
		{src:"images/banner/gum/images/B2.png?1614313836459", id:"B2"},
		{src:"images/banner/gum/images/B3.png?1614313836459", id:"B3"},
		{src:"images/banner/gum/images/bg.jpg?1614313836459", id:"bg"},
		{src:"images/banner/gum/images/bg2.png?1614313836459", id:"bg2"},
		{src:"images/banner/gum/images/light.png?1614313836459", id:"light"}
	],
	preloads: []
};



// bootstrap callback support:

(lib.Stage = function(canvas) {
	createjs.Stage.call(this, canvas);
}).prototype = p = new createjs.Stage();

p.setAutoPlay = function(autoPlay) {
	this.tickEnabled = autoPlay;
}
p.play = function() { this.tickEnabled = true; this.getChildAt(0).gotoAndPlay(this.getTimelinePosition()) }
p.stop = function(ms) { if(ms) this.seek(ms); this.tickEnabled = false; }
p.seek = function(ms) { this.tickEnabled = true; this.getChildAt(0).gotoAndStop(lib.properties.fps * ms / 1000); }
p.getDuration = function() { return this.getChildAt(0).totalFrames / lib.properties.fps * 1000; }

p.getTimelinePosition = function() { return this.getChildAt(0).currentFrame / lib.properties.fps * 1000; }

an.bootcompsLoaded = an.bootcompsLoaded || [];
if(!an.bootstrapListeners) {
	an.bootstrapListeners=[];
}

an.bootstrapCallback=function(fnCallback) {
	an.bootstrapListeners.push(fnCallback);
	if(an.bootcompsLoaded.length > 0) {
		for(var i=0; i<an.bootcompsLoaded.length; ++i) {
			fnCallback(an.bootcompsLoaded[i]);
		}
	}
};

an.compositions = an.compositions || {};
an.compositions['FB59D1E0A848436885A0B7989A76664A'] = {
	getStage: function() { return exportRoot.stage; },
	getLibrary: function() { return lib; },
	getSpriteSheet: function() { return ss; },
	getImages: function() { return img; }
};

an.compositionLoaded = function(id) {
	an.bootcompsLoaded.push(id);
	for(var j=0; j<an.bootstrapListeners.length; j++) {
		an.bootstrapListeners[j](id);
	}
}

an.getComposition = function(id) {
	return an.compositions[id];
}


an.makeResponsive = function(isResp, respDim, isScale, scaleType, domContainers) {		
	var lastW, lastH, lastS=1;		
	window.addEventListener('resize', resizeCanvas);		
	resizeCanvas();		
	function resizeCanvas() {			
		var w = lib.properties.width, h = lib.properties.height;			
		var iw = window.innerWidth, ih=window.innerHeight;			
		var pRatio = window.devicePixelRatio || 1, xRatio=iw/w, yRatio=ih/h, sRatio=1;			
		if(isResp) {                
			if((respDim=='width'&&lastW==iw) || (respDim=='height'&&lastH==ih)) {                    
				sRatio = lastS;                
			}				
			else if(!isScale) {					
				if(iw<w || ih<h)						
					sRatio = Math.min(xRatio, yRatio);				
			}				
			else if(scaleType==1) {					
				sRatio = Math.min(xRatio, yRatio);				
			}				
			else if(scaleType==2) {					
				sRatio = Math.max(xRatio, yRatio);				
			}			
		}
		domContainers[0].width = w * pRatio * sRatio;			
		domContainers[0].height = h * pRatio * sRatio;
		domContainers.forEach(function(container) {				
			container.style.width = w * sRatio + 'px';				
			container.style.height = h * sRatio + 'px';			
		});
		stage.scaleX = pRatio*sRatio;			
		stage.scaleY = pRatio*sRatio;
		lastW = iw; lastH = ih; lastS = sRatio;            
		stage.tickOnUpdate = false;            
		stage.update();            
		stage.tickOnUpdate = true;		
	}
}
an.handleSoundStreamOnTick = function(event) {
	if(!event.paused){
		var stageChild = stage.getChildAt(0);
		if(!stageChild.paused || stageChild.ignorePause){
			stageChild.syncStreamSounds();
		}
	}
}


})(createjs = createjs||{}, gumAn = gumAn||{});
var createjs, gumAn;